"""update database second

Revision ID: 752468ecd9e6
Revises: b365c4d637a7
Create Date: 2022-08-16 02:28:51.099107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752468ecd9e6'
down_revision = 'b365c4d637a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
